language: go

go:
 - '1.8'

before_install:
 - go get github.com/mitchellh/gox

after_success:
 - gox -ldflags "-X main.VersionString=$TRAVIS_TAG" -output "dist/{{.OS}}_{{.Arch}}_{{.Dir}}"

deploy:
 # Deploy to Github Releases
 - provider: releases
   skip_cleanup: true
   api_key:
     secure: IwYdYY59jzqfd77qLx/B9P1pVxEBThE0t5IoF5Jq3K9KKqsRwZ6jIk4qF9NMpoC1Ny7q+W7DCFgzHvIYYFwphbY94eZPL6lVQ88WO0tnb4QxBZ2TLlTSeVlr5Q+4/4Dd569XZsUl1Rm1fM5K+HPJL5Ujhh41FXwrdQam8izNJYGmLJuR5u5cwwJHBqII0SOyaZ6AnUlTfniCJygWqeHGjHlwd7KjoiestblaOnunjtrM75P5Vr7oQMpqgxA/Snu4lq1i2mv4TnVjbWKgQIk8ZV+Op7nGniqj9n6S8p8Q1/c1BEvH+vKRnS5umbhynb9lgpSr1yHlcHYW8SzdEgVHqO8c1W9Rl+FGi+kHruDvbH4El7XdcrCed3neDZa3lIt8MreHY35hx1sjoRXaIbFU0aRu8jjj0v9mZaLn3szd68jnUi7sEVJv83tSXBEDm0WZVowHxJTKFlJv3Ku8wTauwCzGbKhWm5fFCCMnBebG8XF6XY0pyWr69Axel7mlU1UoqUyaig/jdOPHSSHIz430zVQWZgwudQ1/jC5569zy2RvpgucrSLwosZJrOkgqtHqkvi0qP0E5V8OpOjSNG6yfj8LQza1ZqxoST45uHEeyf+ZzLeicRzhv8e9wG5uqLXbZGJgps2nbVAU5es+T/Sx8zfxRPIWP7gpH63HZXcZCrpw=
   file_glob: true
   file: dist/*
   on:
     repo: arnested/sshfpgo
     tags: true

 # Purge the releases badge to get the new release number in there
 - provider: script
   script: curl --silent -X PURGE https://camo.githubusercontent.com/03ec0dd24d599cbb662f8eeaafcda062fbabc7e3/68747470733a2f2f6769746875622d72656c656173652d76657273696f6e2e6865726f6b756170702e636f6d2f6769746875622f61726e65737465642f7373686670676f2f72656c656173652e737667
   on:
     repo: arnested/sshfpgo
     tags: true
