name: Bump version
on:
  push:
    branches:
      - master
jobs:
  bump-version:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: '0'
    - name: Bump version and push tag
      uses: anothrNick/github-tag-action@1.23.0
      env:
        GITHUB_TOKEN: ${{ github.token }}
        WITH_V: true
        DEFAULT_BUMP: patch
